//
// Looking here is probably going to spoil the puzzle. 
// I did not make this server side due to hosting limitations, but it was not meant to be reverse engineered :)
//

































































































const _MS_PER_DAY = 1000 * 60 * 60 * 24;

// a and b are javascript Date objects
function dateDiffInDays(a, b) {
  return Math.floor((b - a) / _MS_PER_DAY);
}

function doDateMagic() {
	var start = new Date("2020-12-05");
	var feb = new Date("2021-02-01");
	var today = new Date();
	if (today > feb) {
		document.getElementById("counter").innerHTML = "Error when computing answer: date is too large.";
		return;
	}

	if (today < start) {
		document.getElementById("counter").innerHTML = "Cannot compute answer for a day before the puzzle began.";	
		return;
	}

	var delta = dateDiffInDays(start, today);


	const data = ['elmhabxwhyzoulantyluhasestxyedzalmcorokceikstexdofclyikgofctheeandieihlpeylureeappvihomeyorrehxppykowieopevourbhapmyhotyousehuotyorrcarseflrevbrihlpeyluthfnkylurezlevbrihlpeylureeappvihomeyorrehxppyqooieopevourbprordhotyoutoulagroseliksubjissfontlfeeayouoownxmbiqionpothlughfcanqimadineeowieopevourbhapmyridhtnlwelmhieiistbntojejuptsavyouoesooryylucakstiilbetithqhewfzarawhaqyousewookedxndwxiteaforvoucxnhasealiyoubvertantbdikkowbrtidlntwxntiqnoizanttantftanvmorbsombthikghapchakgedtithfnmepomeqhindisnltthbsambimteroudhwiqhplxyindbyteeruiesocsomboneblsepgambtooiatecorsbconaguepsindtooiateqogoyackqoslbepiqstijetoqrusqmyikstikctszlosbmyevesakdlexpitptimbtotoydecyindgrasityfthikkilitryaefyfnggoaviqyanayouzantmulljedotncaktimxkeyluunaersqandvourbhavfngdblusfonslfgrxnderrimqhrorghazcepqingiimiqscarseslmeokesavsthbyreposojethfngsfcankotceangbbutqiliqryiilneserkkowtlolokgivbbeekafrxidoclosfngllveiduespiveiosttellffthxtsllveiqcombsatjuchqoohfghazostfdsolneryuydbfyikggrxvitvkispmeglodbveimaefyfnggoaviqyanayouzantmulljedotnglfndazometithjethfnkocwhaqwecluldaotodethbruniimiqedtlgeteerwbreuklimftedqogeqhertellyethbgrextesqteajtheoeseserbbengiindxdrexmsteewavwepiannbdemffwetorkfntakdemqherbsnocighqwecxnnoqwingustvouakdidbfyikggrxvitvwiteyouxndiaefyfnggoaviqythbyllkeveobrikgusaowntellxreylucojingfhopbyouoehampynlwthxtyorreceoosfngteisylutolihomeityrindsyorblipsirballvhopbyoudetiqandvoudlntlfvetlregoetiqihomeyorrehxppyfnthbendfhopbyouoehampymvfribndslifylucaoetocindjelolktoqhewbsteonskvasslmeoketoidmeiateiyevbryokedepervbsthbchakcetlflyxndicimfiyindsollatlbastfmflvingcreeqothlseweogrlundjetaheambssadebazkfrlmmeqellqhemeowixmdecyindgrasityfmflvingeighaefyfnggoaviqyanasookilljatcethejinrbnowkandkoboayinxllocoznlwizxrdteatteerefsortasipeveogonkabrfngmbdowkihomeyorrehxppyiookxtheoshepwichedgbtheobrikgmeaownkoonbmouonsteewizkedpowesegoqtoboingeeroedowk', 'ymadsyrasebosuiystamikgnemidzztyeherssmocuihogttdatoeherlsnuhcsenamdeeitgnasdnopteyrerdanisgnaeddnelssnietvreiswogttpasoferoparortiaatdnohiwedlprosetiitgnhtreferotereinythtnetiosffothtiennhwremeiynnekpererfeidnawtntsnomaaerdniaktfreemhtnetibscatkmoryoowmeherrisemumeayttmetpotrwtiaeihjtsumtaednymebrenatdehetrrbielefrahttamigithebolisgntinaidstahdrtihsraidstahdrtihsraidsterlaylahdrosevyrevyrahdrtirsaellhyravdrevyrehyraidamektiolkoaeysubhtnoyeebilvemeiestahdrtihsraidstahdrtihsraidstosnircdebiylahdrosnioccnieavlbuybnleeiavlbhyraidstahdrotebhtberahdnoseltiyodtnnkwoohiwodtihtresenoylosumhcfoemotograuodnvigetoosamynafsniwhtosamynedamdnisachnraldgytokaaeipssehactnepbeiettehtarerfaeoktrehuaotrgpasheeektrehayllawtnpaeiecfohtsiigmmgemiemtiasrcsotsahitebramiilekejusiswsaeirstbaruedbntusifueftrrhuohgtiehsiusffreniigstlaplraottfehagemhttearppnisgfoafemubstmobedosyogttdaiosthodeeoisatdnkioniwnkwogitoatognagdteabkcotymepandnniokdhnomtkamedeiodtnomtkamegetorhuohgtiacsnmobedogyteemdairknacsuiestahdrtihsraidstahdrtihsraidsterlaylerlaylahdrtissxebytutihsraidsterlaylahdresyxubitstahdrhtsiabtrahitrmiaisgnotebhtsimazaniigstahdrtihsraidstahdrtihsraidstosnaoniygnylahdrosnuvaioadlbuyenjnyobaylahdrtihsratdboteehabdrabybkionwwiritgnamedemafomsuubbtiegnafomsusiujtsosumhcomerufynuoesweahptoelpjesudtnoutdnretsnaidtsahwtiritgndsmenaidgntimsneatllcyahllneiggnnaidstbaroiestushccaoherotisitanormoyboyruesflhoymogidujtsahettinayduoerrtiygnotifdnnaponenilgnioearrbliilnaitedaadnoyrupecanitgehlfooardnohipgnofjrsuatibotdfviniietnreevtnoitnahotenilttelunggtehttanoletiltseapkrhtneueerakoyfuniidytuoererdatysoattrosonywuoacwniretirhgwtorgnoyrunetovenelcsoyeuoerembmrehttaadnmtioyrulpyagstoatebniaibmcieptnmatereosoywuiretodnwwarobdtutinstohtregithowdrosoytuyrnaweowdrubytuoahethtneweowdrnayduoendegaoowdrobdtuoycunaftnitdehowdrhohwreieiswtahitiswtahitiswtehersitilbhalbhalbhaahahhaahguhhhhhhhhishrleoloyauksdeofirfnroamitnonohwtainhclosaobttmosirwtiniogrupsiyhsrewetithehenswidhdseeeemolisgntiehhslabfildnisorghootdehhnoelnsywaahflfotioysueehwtadidiahahpsaemknahwtaenswsiwainkcobttmodidiehapdisaoohtaseytrforoseeehwtahskaseeprasergaeettslpyaowlubdteahstenkalytiltteihfehwdyeonshtcemouewptihhsiwoinedsatihsrandioitisnsititsterlaylhtwerotstihsramdkaseemowdnrehwiyidndttihknfohttaifsritstahdrahdrotlaelivtateehrpseuserotrcaeettihsrahdratddosomoteihgnsaogdosahtlesattihgndidihttaawasrlaeydrgaeitstahdrtihsrasdhoratdahhtiessetlanifgortmehabdrewlllihliotsihbmhysiepatdrlailendesicaelevdrsiugsiceelevdrsiugsiiellamekihpmyaoftrohesedivuolseidsveoisuilseelhtmiodlatlehetiduossutffhtwerotkahstetrrbiylnaudbnaearlbhyraadrlgithinkcobttmotiihknhskaseepraneeesdotifdnuowtahstahekpsaeernsxebtgiihwtliblceuaestihsraidstotatllhyraidstahdrtitstolaylahdrtihsraidstotatllhyraidevogftroutennafdmaeeevyrnokeonswymanemcinahtleipitifstosrfaeikhnrad', 'woaaahnevraginwllsegetheestfmeeveaganwilshtakawamyfeedmanwewntfrgetheaywfouhtfrthrigttoealttlbitaugtynvergaiwilthehokydorslmneeraainillbebllidannevraginwllioubitwenmmumysasimmircleeveaganneeraainilleliebeindoornevraginnwwenowearrevltigchldrnliingnreoltngtmesesigreoltngsngssinrevltigrhmesellereoltngcildentlourevltigsdneadwelhaethtruchbllbltigweereoltngwareevotinchidrelivngirevltigtieswsinrevltigsogsuingevotinrhyeswllbrevltigchldrntiourevotinsdoeanwelhavtherunhbulbotinwerrevltigweillecoeasreaingoartakoutourockystcksndueitsasordeveaganwilweeigorewelfinoutherthehalissoreandrawudeictresnthboaditnotnsutinwerrevltigweanslhowelkeienoghousaewrngwongsrihteerynenrtyoswreaittebinauhtyheyaywougttotaynsiethlinbutfweisoeyatheameimeherisnthigthtthtruchbllcndohecntaehehameradshyouevethoghtouculdushstofarutterenogingackowwareevotinomenwelsigusngwllbrevltigitsluearrevltigwerervolinghilreniviginevotintimsweingevotinsonsusngrvolinghymswelbeevotinchidretilurrvolingdonandellavehetuncbulbolingereevotinweaereoltngcildenlvininrvolingimewesngrvolingongusigreoltngrymewelbervolinghilrenilorreoltngsonendwllhvetetrnchulloltngwrervoling', 'wheiwajusakieveythngiidwstoeliehiundrmykinyfaherlwasthughifiassronandougtnoliksomalbtrosidegitoftinooktmeowelesandoldngmbrethtyinhartorpreswhtscredimtdeahitasntthteaytoehitypofmntoreahefeelwasotihislanndtebetpatofeishatewoldnseemnomyfthessoimntthimaeofhatedrameofwthtestenghofparaantheatincefjostilcoldnbeteontoehowathddoeanmirorwatwsnoinmsoiumpdinydramsndfundnesapeaybiwettoxtrmesfletheandaceuttewoldsemsrigternchsoftheroudantheirsemeligterwasrofundndieltoprudjsttlivoutoudmnomyfthessoimntimgeowhahedeamdofithhesrenthospataadthpatencofjbstllculdtbeheoetochohateddneadmirorhatasntinethendesstorofepecatinswrininsdemminwormedwniameoaraliatinanifondaaytturitaountosethticuldustememnomyfthessoimntthimaeofhatedrameofwthtestenghofparaantheatincefjostilcoldnbeteontoehowathddoeanmirorwatwsnoinm', 'insleephesangtomeindreamshecamethatvoicewhichcallstomeandspeaksmynameanddoidreamagainfornowifindthephantomoftheoperaisthereinsidemymindsingonceagainwithmeourstrangeduetmypoweroveryougrowsstrongeryetandthoughyouturnfrommetoglancebehindthephantomoftheoperaisthereinsideyourmindthosewhohaveseenyourfacedrawbackinfeariamthemaskyouwearitsmetheyhearmyspiritandmyvoiceinonecombinedthephantomoftheoperaisthereinsidemymindinallyourfantasiesyoualwaysknewthatmanandmysterywerebothinyouandinthislabyrinthwherenightisblindthephantomoftheoperaisthereinsidemymindsingmyangelofmusichestherethephantomoftheoperasingaahsingaahsingformeaahsingmyangelofmusicaahsingformeaahihavebroughtyoutotheseatofsweetmusicsthronetothiskingdomwhereallmustpayhomagetomusicmusicyouhavecomehereforonepurposeandonealonesincethecallwhenifirstheardyousingihaveneededyouwithmetoservemetosingformymusicmymusic', 'ifthworlisgonaentomorowwllownginorrowontetusnywhreyollfidallhestengtyounedisnsidlikeoseionriingcosstetiddontetthsmomntpasbycmeoneroimymidlenmefiintrublesmygmejutgivittholdkowhothersnobtterimetannodontiveuanddntgieinyahifourehinknsinorswmohyahcoragesyouclaitofaewheherosyoumiddenamandhroisurmidlenmewelthasnicboysutmiesjenifemymahinetheyadeaealpedicionisnotcieneficionteresothigwecndoaallwyareouwatingorthbottmtofllnothetmetoroptebigeachallalforneanonefrallllfooneadoneoralallfronendonforalcomonheoismmiddenamallrghtfxintoublismyamejstgieitteoldnowhwtheesnoettetimehannwdongivepandontgveinfyouethikinsnkorwimcuragisyorclamtofmewhnherisyormidlenaeanderoimymidlenmealightoysltsdohistreehroesotheescuteamftretothtopugosoomeoherosouriddlnameixinroubeisorgamjustiveitheodknohowteresobetertiethanowdntgieupaddongivenifyuretinkisinkrswicourgeisourcaimtfamehenhroisourmddleameadherisoumiddenamandhroisurmidlenmeheoisormidlenae', 'tiawtiroftiawtiroftiawtiroftiawtiroftiawtiroftiawtiroftiawtiroftiawtiroftiawtiroftiawtiroftiawtiroftiawotnilliwminehtdeidevahynamosnehwevilallitsminosaeraserehtfidnasekatsimruoekamewdnakaerbewdnallafewllafewdnaesirewyawynagnivilpeekewdnasekattidnasekattidnasekattistniasehtdnasrennisehtneewtebetanimircsidtnseodefiltiroftiawotgnilliwmitiroftiawtiroftiawotgnilliwmitinmaddognehtevivruswefosnehwevirhtotsmeesehnosaeraserehtfidnasekatsehtsesiarehdnasyalpehemagehtsegnahcehyawynagninniwspeekehdnasekatehdnasekatehdnasekatehtniartseronstibihxeehetatisehtnseodnotlimahseohssihniekiltisitahwemitemitemitemitonsetsawehsseltnelersiecapsnotlimahesolesolesolesolesolotgnihtonsahehevorpotgnihtemossahehbmilcbmilcbmilcbmilcllihpusseldnenasecafnotlimahtiawtiawtiawtiawnigniylmaillitsgnidnatstonmitiroftiawtiroftiawtiroftiawtiroftiawetalgninnurrodnihebgnillaftonmilanigironamaielbatiminimaitiroftiawtiroftiawtiroftiawtiroftiawlortnocnaciefilnignihtenoehtmaitiroftiawotgnilliwmitiroftiawtiroftiawotgnilliwmideidsahemsevolohwenoyrevenehwevilallitsminosaeraserehtfidnasekatsimruoekamewdnakaerbewdnallafewdnaesirewyawynagnivilpeekewdnasekattidnasekattidnasekattistniasehtdnasrennisehtneewtebetanimircsidtnseodhtaedtcetorpotycagelatsujsnoitcurtsniontfelyehtdeidyehtnehwtcepsertcepsertcepserdednammocrehtafymsuinegsuinegasawrehtomymayhcaetayhcaetayhcaetayhcaettnowsnmyhdnaseilimohehttahtsgnihteraerehttubrehcaerprehcaerprehcaerprehcaerpenotsmirbdnaerifasawrehtafdnargymtiroftiawotgnilliwmitiroftiawotgnilliwminehtdeirtevahynamosnehwedisrehybminosaeraserehtfidnasekatsimruoekamewdnakaerbewdnayrcewdnahgualewyawynagnivolpeekewdnasekattidnasekattidnasekattistniasehtdnasrennisehtneewtebetanimircsidtnseodevolenimsehsaisodoehtaigroegfollapeeknacehtubenilniseinolocehtpeekotgniyrtsehaigroegniedishsitirbehtnosehyawasidnabsuhrehelihwmrawdebehtgnipeekmiyadyreverettelaemsetirwaisodoeht', 'whrhasthstarlightgondarkisthdayhowcanifindmywayhomhomisanmptydramlosttothnightfathriflsoalonyoupromisdyoudbthrwhnvrinddyouwhnvricallyournamyournotanywhrimtryingtoholdonjustwaitingtoharyourvoiconwordjustawordwilldotondthisnightmarwhnwillthdawningbrakohndlssnightslplssidramofthdaywhnyouwrbymysidguidingmypathfathricantfindthwayyoupromisdyoudbthrwhnvrinddyouwhnvricallyournamyournotanywhrimtryingtoholdonjustwaitingtoharyourvoiconwordjustawordwilldotondthisnightmariknowthatthnightmustndandthatthsunwillrisandthatthsunwillrisiknowthatthcloudsmustclarandthatthsunwillshinandthatthsunwillshinsimbaandiknowthatthnightmustndandthatthsunwillrisandthatthsunwillrisiknowthatthcloudsmustclarandthatthsunwillshinandthatthsunwillshinrpattondiknowysiknowthsunwillrisysiknowiknowthcloudsmustclariknowthatthnightmustndiknowthatthsunwillrisandillharyourvoicdpinsidiknowthatthnightmustndandthatthcloudsmustclarthsunthsunwillristhsunthsunwillris'];

	var res = '';
	for (var i = 0; i < 8; i++) {
		res = res + data[i][delta % data[i].length];
	}
	document.getElementById("waitanswer").innerHTML = res.toUpperCase();
	document.getElementById("counter").innerHTML = "(It's been " + delta + " days since the start of the puzzle.)";
}

doDateMagic();